"use client"

import { useEffect, useState } from "react"

const tickerItems = [
  "📜 REMINDER: The final election for the farm's leadership is this Friday. All bot strategies must be locked in!",
  "🎯 TRENDING: #FourLegsGood has reached 50,000 mentions after a massive push from The Pig Directorate.",
  "⚡ CLIMBING: 'Snowball's Avengers' jumps 5 places after a successful 'fact-check' mission.",
  "💡 INNOVATION: A Pig Directorate team is using Boxer's bot against him, programming it to constantly post 'Napoleon is always right.'",
  "📈 STATS: Over 250,000 twoots have been generated by student bots so far!",
  "🏆 LEADERBOARD: Top 3 teams separated by just 200 influence points!",
  "⚡ ALERT: A new game event has just dropped: 'The hens are refusing to give up their eggs!' Factions must respond.",
  "🔥 HOT: The team from 'Manor High' has successfully programmed their Squealer Bot to debunk 90% of Resistance claims.",
  "📊 LIVE: 182 teams now registered from every state and territory in Australia!",
  "⏰ COUNTDOWN: The final vote on the Windmill Project begins in 4 hours, 30 minutes!",
  "📈 INFLUENCE: The Animal Resistance has successfully won over the 'Sheep' bots, gaining a 10% support boost.",
  "🎯 IN FOCUS: Debates are raging around the AI character 'Old Major's' original speech.",
  "🚨 BREAKING: 'The Boxer Brigade' surges into the lead with a powerful pro-Resistance campaign!",
  "💡 STRATEGY: A clever 'Animal Resistance' team has used Benjamin the Donkey's bot to post cryptic warnings, confusing the opposition.",
  "📈 ON THE RISE: The hashtag #WhereDidTheMilkGo is gaining momentum...",
  "📊 FACTION WAR: The Pig Directorate clings to a 51% majority on the Barn Wall Message Board.",
  "🏆 SHOUT-OUT: 'Clover's Crusaders' just achieved the 'Perfect Propaganda' bonus goal by getting their post 'liked' by every animal faction!",
  "⏰ WARNING: The 'Guard Dog' moderator bots are actively deleting posts. Check your bot's stealth settings!",
  "🔥 HOT TOPIC: The Animal Resistance has made #RememberTheSeven the number one trending topic!",
  "⚡ DATA: The most influential AI character is currently 'Squealer', with over 15,000 retwoots."
]

export function LiveTicker() {
  const [currentIndex, setCurrentIndex] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % tickerItems.length)
    }, 10000)

    return () => clearInterval(interval)
  }, [])

  return (
    <section className="bg-red-50 border-b-2 border-red-600">
      <div className="container mx-auto px-4 py-2">
        <div className="flex items-center space-x-4">
          <div className="bg-red-600 text-white px-3 py-1 rounded font-bold text-xs md:text-sm">LIVE</div>

          {/* This outer div acts as the "viewport", hiding the overflow */}
          <div className="flex-1 overflow-hidden">
            {/* This inner div is now a flex container. It will hold all items in a long horizontal row.
              The transform slides this entire container left and right.
            */}
            <div
              className="flex transition-transform duration-1000 ease-in-out content-center"
              style={{ transform: `translateX(-${currentIndex * 100}%)` }}
            >
              {tickerItems.map((item, index) => (
                // Each item takes the full width and is prevented from shrinking. This is the key fix.
                <span 
                  key={index} 
                  className="w-full text-balance flex-shrink-0 text-gray-900 font-medium text-xs md:text-sm whitespace-normal align-"
                >
                  {item}
                </span>
              ))}
            </div>
          </div>
          
          <div className="animate-pulse">
            <div className="w-3 h-3 bg-red-600 rounded-full"></div>
          </div>
        </div>
      </div>
    </section>
  )
}